[server]
addr = "0.0.0.0"
port = 80

[account-factory]
cache-capacity        = 2 # low value for demo purposes!
cache-buffer          = 7
entity-cmd-buffer     = 7
entity-snapshot-after = 2 # low value for demo purposes!

# NATS event log
[evt-log]
server-addr = "localhost:4222"
setup       = true

# NATS snapshot store
[snapshot-store]
server-addr = "localhost:4222"
setup       = true
